// Code generated by protoc-gen-tinyrpc.

package message

// ArithService 运算服务
type ArithService struct{}

// Add 算数加法
func (this *ArithService) Add(args *ArithRequest, reply *ArithResponse) error {
	reply.C = args.A + args.B
	return nil
}

// Sub 算数减法
func (this *ArithService) Sub(args *ArithRequest, reply *ArithResponse) error {
	reply.C = args.A - args.B
	return nil
}

// Mul 算数乘法
func (this *ArithService) Mul(args *ArithRequest, reply *ArithResponse) error {
	reply.C = args.A * args.B
	return nil
}

// Div 算数除法
func (this *ArithService) Div(args *ArithRequest, reply *ArithResponse) error {
	reply.C = args.A / args.B
	return nil
}
