// Code generated by protoc-gen-tinyrpc.

package message

import (
	"github.com/zehuamama/tinyrpc"
	"net"
)

// ArithService Defining Computational Digital Services
type ArithServiceClient struct {
	client *tinyrpc.Client
}

func NewArithServiceClient(conn net.Conn) ArithServiceClient {
	return ArithServiceClient{client: tinyrpc.NewClient(conn)}
}

// Add addition
func (this *ArithServiceClient) Add(args *ArithRequest, reply *ArithResponse) error {
	return this.client.Call("ArithService.Add", args, reply)
}

// Sub subtraction
func (this *ArithServiceClient) Sub(args *ArithRequest, reply *ArithResponse) error {
	return this.client.Call("ArithService.Sub", args, reply)
}

// Mul multiplication
func (this *ArithServiceClient) Mul(args *ArithRequest, reply *ArithResponse) error {
	return this.client.Call("ArithService.Mul", args, reply)
}

// Div division
func (this *ArithServiceClient) Div(args *ArithRequest, reply *ArithResponse) error {
	return this.client.Call("ArithService.Div", args, reply)
}
