// Code generated by protoc-gen-go. DO NOT EDIT.
// source: header.proto

/*
Package header is a generated protocol buffer package.

It is generated from these files:
	header.proto

It has these top-level messages:
	RequestHeader
	ResponseHeader
*/
package header

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Const int32

const (
	Const_ZERO           Const = 0
	Const_MAX_HEADER_LEN Const = 1024
)

var Const_name = map[int32]string{
	0:    "ZERO",
	1024: "MAX_HEADER_LEN",
}
var Const_value = map[string]int32{
	"ZERO":           0,
	"MAX_HEADER_LEN": 1024,
}

func (x Const) String() string {
	return proto.EnumName(Const_name, int32(x))
}
func (Const) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RequestHeader struct {
	IsCompressed bool   `protobuf:"varint,1,opt,name=is_compressed,json=isCompressed" json:"is_compressed,omitempty"`
	Method       string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Id           uint64 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	RequestLen   uint32 `protobuf:"varint,4,opt,name=request_len,json=requestLen" json:"request_len,omitempty"`
	Checksum     uint32 `protobuf:"varint,5,opt,name=checksum" json:"checksum,omitempty"`
	Ttl          uint64 `protobuf:"varint,6,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *RequestHeader) Reset()                    { *m = RequestHeader{} }
func (m *RequestHeader) String() string            { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()               {}
func (*RequestHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestHeader) GetIsCompressed() bool {
	if m != nil {
		return m.IsCompressed
	}
	return false
}

func (m *RequestHeader) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RequestHeader) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestHeader) GetRequestLen() uint32 {
	if m != nil {
		return m.RequestLen
	}
	return 0
}

func (m *RequestHeader) GetChecksum() uint32 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func (m *RequestHeader) GetTtl() uint64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type ResponseHeader struct {
	IsCompressed bool   `protobuf:"varint,1,opt,name=is_compressed,json=isCompressed" json:"is_compressed,omitempty"`
	Id           uint64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Error        string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	ResponseLen  uint32 `protobuf:"varint,4,opt,name=response_len,json=responseLen" json:"response_len,omitempty"`
	Checksum     uint32 `protobuf:"varint,5,opt,name=checksum" json:"checksum,omitempty"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseHeader) GetIsCompressed() bool {
	if m != nil {
		return m.IsCompressed
	}
	return false
}

func (m *ResponseHeader) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResponseHeader) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResponseHeader) GetResponseLen() uint32 {
	if m != nil {
		return m.ResponseLen
	}
	return 0
}

func (m *ResponseHeader) GetChecksum() uint32 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "header.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "header.ResponseHeader")
	proto.RegisterEnum("header.Const", Const_name, Const_value)
}

func init() { proto.RegisterFile("header.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0x84, 0x40,
	0x18, 0xc7, 0x1b, 0x57, 0xc5, 0xfd, 0x56, 0x45, 0xbe, 0x22, 0x86, 0x2e, 0xd9, 0x06, 0x21, 0x1d,
	0xba, 0xf4, 0x04, 0xcb, 0x26, 0xec, 0x61, 0x2b, 0x98, 0x53, 0x74, 0x91, 0xd2, 0x0f, 0x94, 0x56,
	0xc7, 0x66, 0x66, 0xef, 0x3d, 0x47, 0xaf, 0xd0, 0x4b, 0x46, 0xa3, 0x49, 0xb7, 0xd8, 0xdb, 0xfc,
	0x7e, 0x03, 0x7f, 0x7e, 0xf0, 0x41, 0x58, 0xd3, 0x4b, 0x45, 0xea, 0xa6, 0x57, 0xd2, 0x48, 0xf4,
	0x07, 0x5a, 0x7e, 0x31, 0x88, 0x04, 0xbd, 0xef, 0x49, 0x9b, 0x8d, 0x35, 0x78, 0x09, 0x51, 0xa3,
	0x8b, 0x52, 0xb6, 0xbd, 0x22, 0xad, 0xa9, 0xe2, 0x2c, 0x65, 0x59, 0x20, 0xc2, 0x46, 0xaf, 0x27,
	0x87, 0xa7, 0xe0, 0xb7, 0x64, 0x6a, 0x59, 0x71, 0x27, 0x65, 0xd9, 0x5c, 0x8c, 0x84, 0x31, 0x38,
	0x4d, 0xc5, 0x67, 0x29, 0xcb, 0x5c, 0xe1, 0x34, 0x15, 0x9e, 0xc3, 0x42, 0x0d, 0xeb, 0xc5, 0x8e,
	0x3a, 0xee, 0xa6, 0x2c, 0x8b, 0x04, 0x8c, 0x6a, 0x4b, 0x1d, 0x9e, 0x41, 0x50, 0xd6, 0x54, 0xbe,
	0xe9, 0x7d, 0xcb, 0x3d, 0xfb, 0x3b, 0x31, 0x26, 0x30, 0x33, 0x66, 0xc7, 0x7d, 0xbb, 0xf6, 0xf3,
	0x5c, 0x7e, 0x32, 0x88, 0x05, 0xe9, 0x5e, 0x76, 0x9a, 0x0e, 0xc9, 0x1d, 0xb2, 0x9c, 0x29, 0xeb,
	0x04, 0x3c, 0x52, 0x4a, 0x2a, 0x5b, 0x3a, 0x17, 0x03, 0xe0, 0x05, 0x84, 0x6a, 0x1c, 0xff, 0x53,
	0xbb, 0xf8, 0x75, 0xff, 0xe4, 0x5e, 0x5f, 0x81, 0xb7, 0x96, 0x9d, 0x36, 0x18, 0x80, 0xfb, 0x9c,
	0x8b, 0xc7, 0xe4, 0x08, 0x8f, 0x21, 0xbe, 0x5f, 0x3d, 0x15, 0x9b, 0x7c, 0x75, 0x97, 0x8b, 0x62,
	0x9b, 0x3f, 0x24, 0x1f, 0xc1, 0xab, 0x6f, 0x2f, 0x70, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x16,
	0xf7, 0x24, 0xb5, 0x91, 0x01, 0x00, 0x00,
}
